language: node_js
os:
  - linux
dist: trusty
sudo: false
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE db;'
install:
  - npm install
script:
  - npm test
